{"uuid": "33e557fc-b743-41eb-b60b-fc7a79a63a97", "children": ["bfa243b0-6d3f-4114-ae0f-124a0e53cfd3"], "befores": [{"name": "_Class__pytest_setup_method", "status": "passed", "start": 1597712832079, "stop": 1597712834519}], "afters": [{"name": "_Class__pytest_setup_method::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebDriver' object has no attribute 'resetApp'\n", "trace": "  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\_pytest\\python.py\", line 774, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\_pytest\\python.py\", line 676, in _call_with_optional_argument\n    func()\n  File \"C:\\sourceCode\\PycharmProjects\\UI_Test\\test_case\\test_app\\test_email.py\", line 22, in teardown_method\n    self._driver.resetApp()\n"}, "start": 1597712849866, "stop": 1597712849868}], "start": 1597712832079, "stop": 1597712849868}