{"uuid": "3e394fca-4232-4cc1-93a2-9650d02ce283", "children": ["ede71d8e-4cba-4e6a-adab-aee8ef4634a1"], "befores": [{"name": "_Class__pytest_setup_method", "status": "passed", "start": 1597712914363, "stop": 1597712916688}], "afters": [{"name": "_Class__pytest_setup_method::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebDriver' object has no attribute 'resetApp'\n", "trace": "  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\_pytest\\python.py\", line 774, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\xue\\.conda\\envs\\auto_test\\lib\\site-packages\\_pytest\\python.py\", line 676, in _call_with_optional_argument\n    func()\n  File \"C:\\sourceCode\\PycharmProjects\\UI_Test\\test_case\\test_app\\test_email.py\", line 22, in teardown_method\n    self._driver.resetApp()\n"}, "start": 1597712921567, "stop": 1597712921568}], "start": 1597712914363, "stop": 1597712921568}